name: Geometric-Tm
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - tqdm
  - request
  - prody
  - sortednp
  - torchinfo
  - scikit-learn
  - transformers
  - sentencepiece
  - networkx
